$(function(){
    $(".box").on({
        mouseover:function(){
            $(this).find(".all").stop().slideDown();
        },
        mouseout:function(){
            $(this).find(".all").stop().slideUp();
        }
    })
});